# Generated by Django 5.2.3 on 2025-06-28 05:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_appointment_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='VD: GIAM10, KHAITRUONG', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm'), ('fixed', 'Số tiền cố định')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Nếu là phần trăm, nhập 10 cho 10%. Nếu là tiền cố định, nhập số tiền.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền trước giảm giá', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền sau giảm giá', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voucher_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.voucher'),
        ),
    ]
