# Generated by Django 5.2.3 on 2025-07-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_product_invoicedetail_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_code',
            field=models.CharField(blank=True, help_text='Mã hồ sơ hoặc mã khách hàng thân thiết', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('transfer', 'Chuyển khoản')], max_length=50),
        ),
    ]
