# Generated by Django 5.2.3 on 2025-07-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_rename_amount_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ví dụ: Thẻ 10 triệu', max_length=100)),
                ('value', models.DecimalField(decimal_places=2, help_text='Giá trị của thẻ, ví dụ: 10000000', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='gift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.giftcard'),
        ),
    ]
