# Generated by Django 5.2.3 on 2025-07-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_giftcard_invoicedetail_gift_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số dư tín dụng/tiền tích điểm của khách', max_digits=12),
        ),
    ]
