# Generated by Django 5.2.3 on 2025-07-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_customer_credit_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số dư tín dụng/tiền tích điểm của khách', max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_code',
            field=models.CharField(blank=True, help_text='Mã hồ sơ hoặc mã khách hàng thân thiết', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='name',
            field=models.CharField(help_text='Ví dụ: Thẻ 10 triệu', max_length=100),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Giá trị của thẻ, ví dụ: 10000000', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền sau giảm giá', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền trước giảm giá', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0, help_text='Số lượng tồn kho'),
        ),
    ]
